name: 'release-please-action'
description: 'automated releases based on conventional commits'
author: Google LLC
inputs:
  token:
    description: 'GitHub token for creating and grooming release PRs, e.g., secrets.GITHUB_TOKEN'
    required: true
  fork:
    description: 'should the PR be proposed from a fork (does not work with secrets.GITHUB_TOKEN)'
    required: false
  clean:
    description: 'Should stale release PRs be closed post release? Defaults to true'
    required: false
  package-name:
    description: 'name of the distributions releases are being created for, e.g., "name" in package.json, or "setup.py"'
    required: true
  release-type:
    description: 'what type of release is this, one of (ruby, python, node, terraform-module)'
    required: true
  bump-minor-pre-major:
    description: 'should breaking changes before 1.0.0 produce minor bumps'
    required: false
  path:
    description: "create a release from a path other than the repository's root"
    required: false
  monorepo-tags:
    description: 'add prefix to tags and branches, allowing multiple libraries to be released from the same repository'
    required: false
  changelog-path:
    description: 'specify a CHANGELOG path other than the root CHANGELOG.md'
    required: false
  changelog-types:
    description: 'changelog commit types'
    required: false
  command:
    description: 'release-please command to run, either "github-release", or "release-pr" (defaults to running both)'
    required: false
  version-file:
    description: 'provide a path to a version file to increment (used by ruby releaser)'
    required: false
  label:
    description: 'comma-separated list of PR labels to apply'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
